### ISSUE TITLE
aarch64 build is broken

### ISSUE THREAD

**Issue by hfiguiere** [flathub/io.github.dbchoco.muezzin#1] opened 2022-04-08 03:21 UTC
The aarch64 build is broken

```
 $ flatpak run io.github.dbchoco.muezzin
/app/bin/muezzin/muezzin: /app/bin/muezzin/muezzin: cannot execute binary file
```

If I do 
```
$ file /app/bin/muezzin/muezzin
/app/bin/muezzin/muezzin: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=9451f4efa14feaa71717ded5a7d7857cdf56dd3f, stripped
```

You package a x86_64 binary on aarch64.

**Comment by DBChoco** [comment] 2022-04-08 07:21
Thanks for noticing!
Does it work now that I switched from node to i386 ?

**Comment by DBChoco** [comment] 2022-04-08 07:46
I get this error now: `Unknown extension 'org.freedesktop.Sdk.Compat.i386' in runtime`
Would you know how to fix it ?

**Comment by DBChoco** [comment] 2022-04-08 08:06
For now I just dropped aarch64 support, if you can help me make it run on aarch64 systems architectures I'd appreciate it, but otherwise you can close the issue I think

**Comment by hfiguiere** [comment] 2022-04-08 12:30
> Thanks for noticing! Does it work now that I switched from node to i386 ?

aarch64 is NOT i386, It has nothing to do with it.

aarch64 is ARM v8 64 bits.

**Comment by hfiguiere** [comment] 2022-04-08 12:36
You broke it with this commit

https://github.com/flathub/io.github.dbchoco.muezzin/commit/9d19027ff1f308766863b18295e72e29fb869d83

The appimage is x86_64 only.

And now there are broken build in aarch64 left in the repository.

**Comment by DBChoco** [comment] 2022-04-08 12:54
The problem is that the tar.gz method didn't want to work
https://github.com/flathub/flathub/issues/2993

**Comment by hfiguiere** [comment] 2022-04-08 12:57
but you didn't wait for somebody to even try to help...

You don't get 4 hour dev technical support with MILLION DOLLAR contracts. So imagine with a bunch of volunteers that might not be available at the same time as you are.

You probably needed to regenerate the package list. That's what it looks like to me.

**Comment by DBChoco** [comment] 2022-04-08 13:00
I regenerated it multiple times, using npm or yarn and adding different arguments each time.
I do admit I was a bit hasty, should have taken some time.

Do you have any other clues as to how I could fix it ? If I can I'd like to go back to the older version

**Comment by DBChoco** [comment] 2022-04-08 18:02
Managed to fix it somehow, I'll update https://github.com/flathub/flathub/issues/2993 in case any one needs it.
Thanks for all the help!

**Closed as completed by DBChoco** 2022-04-08 18:02 UTC

**Comment by DBChoco** [comment] 2022-04-09 23:04
Ok, I managed to find the fix: https://github.com/flathub/flathub/issues/2993
I hope it help someone in the future in case you encounter someone in the same problem as me.
Have a nice day !
